export const pokemonTypeColor: Record<string, string> = {
  normal: 'background__normal',
  fire: 'background__fire',
  water: 'background__water',
  electric: 'background__electric',
  grass: 'background__grass',
  ice: 'background__ice',
  fighting: 'background__fighting',
  poison: 'background__poison',
  ground: 'background__ground',
  flying: 'background__flying',
  psychic: 'background__psychic',
  bug: 'background__bug',
  rock: 'background__rock',
  ghost: 'background__ghost',
  dragon: 'background__dragon',
  dark: 'background__dark',
  steel: 'background__steel',
  fairy: 'background__fairy',
  unknown: 'background__unknown',
};
