coverage:
  range: 60..90
  round: down
  precision: 2
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        base: auto
      apps_react-lab:
        target: 85%
        paths:
          - 'apps/react-lab/src/app'
      libs_react-components:
        paths:
          - 'libs/react-components/src/lib'
        target: 90%
      libs_data-access-pokemon:
        paths:
          - 'libs/data-access-pokemon/src/lib'
        target: 90%
      libs_util-i18n:
        paths:
          - 'libs/util-i18n/src/lib'
        target: 90%
    patch:
      default:
        target: auto
        threshold: 2%
        base: auto

comment:
  layout: 'reach, diff, flags, components, files'
  behavior: new
  require_changes: false
  require_base: false
  require_head: false
  branches:
    - 'main'

component_management:
  individual_components:
    - component_id: apps_react-lab
      name: apps_react-lab
      paths:
        - apps/react-lab/src/app
    - component_id: libs_react-components
      name: libs_react-components
      paths:
        - libs/react-components/src/lib
    - component_id: libs_data-access-pokemon
      name: libs_data-access-pokemon
      paths:
        - libs/data-access-pokemon/src/lib
    - component_id: libs_util-i18n
      name: libs_util-i18n
      paths:
        - libs/util-i18n/src/lib

ignore:
  - documentation
  - dist
  - tools
  - '**/test-setup.mjs'
  - '**/tests/**'
  - '**/constants/**'
  - '**/enums/**'
  - '**/interfaces/**'
  - '**/*.enum.*'
  - '**/*.type.*'
  - '**/*.interface.*'
  - '**/*.stories.*'
  - '**/main.tsx'
  - '**/.eslintrc.js'
  - '**/global.d.ts'
  - '**/index.ts'
